replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "4"
    memory: "8192Mi"
    ephemeral-storage: "600Mi"
  requests:
    cpu: "3"
    memory: "7168Mi"
    ephemeral-storage: "500Mi"
